#!/bin/sh
# this probably isn't right, but postgres 
exec /sbin/setuser postgres /usr/lib/postgresql/9.1/bin/postgres \ 
    -D /var/lib/postgresql/9.1/main  \
    -c config_file=/etc/postgresql/9.1/main/postgresql.conf
